#!/usr/bin/env ruby

usage = 'greet [options] THING'
desc = 'Greet prints one kind of greeting.'

def main(argv=[], opts={})
  thing = ARGV[0]
  raise 'THING argument is required!' unless thing
  puts "hello #{thing}"
end

require 'optparse'
options = {}
OptionParser.new do |opts|
  opts.banner = desc
  opts.separator "Usage: #{usage}"
  opts.on_tail('--version') do
    puts '0.1.0'
    exit 0
  end
  opts.on_tail('-h', '--help') do
    puts opts
    exit 0
  end
end.parse!

begin
  main(ARGV)
rescue => ex
  STDERR.puts ex.message
  exit 1
end