#!/usr/bin/env ruby
require 'greet'

usage = 'greet [options] THING'
desc = 'Greet prints one kind of greeting.'

def main(argv=[], opts={})
  thing = ARGV[0]
  raise 'THING argument is required!' unless thing
  greeter = Greet::Greeter.new
  puts greeter.greeting(thing)
end

require 'optparse'
options = {}
OptionParser.new do |opts|
  opts.banner = desc
  opts.separator "Usage: #{usage}"
  opts.on_tail('--version') do
    puts Greet::VERSION
    exit 0
  end
  opts.on_tail('-h', '--help') do
    puts opts
    exit 0
  end
end.parse!

begin
  main(ARGV)
rescue => ex
  STDERR.puts ex.message
  exit 1
end